#!/usr/bin/env ruby

require_relative 'lib/dot_file_manager.rb'
require_relative 'lib/simple_cli_wrapper.rb'

def main
  SimpleCLIWrapper.new(ARGV, DotFileManager).perform
end

if __FILE__ == $0
  main
end
