#!/usr/bin/env bash

# Set starting dir
cd ~/code

# Create Session
SESSION_NAME=recruiting
tmux new-session -d -s $SESSION_NAME

# Create running window
tmux select-window -t $SESSION_NAME:1
tmux rename-window 'running'
tmux split-window -h
tmux split-window -v
tmux select-pane -t 0
tmux split-window -v

tmux select-pane -t 0
tmux send 'cd ~/code/toggle/recruiting_automation-server' ENTER 'bundle exec rails s' ENTER
tmux select-pane -t 1
tmux send 'cd ~/code/toggle/recruiting_automation-client-web' ENTER 'sleep 2' ENTER 'ember s' ENTER

# Create server window
tmux new-window -d -t $SESSION_NAME:2 -n 'server'
tmux select-window -t $SESSION_NAME:2
tmux split-window -h
tmux split-window -v

tmux select-pane -t 0
tmux send 'cd ~/code/toggle/recruiting_automation-server' ENTER 'vim' ENTER
tmux select-pane -t 1
tmux send 'cd ~/code/toggle/recruiting_automation-server' ENTER 'vim ~/code/working_notes/recruiting_server.rb' ENTER
tmux select-pane -t 2
tmux send 'cd ~/code/toggle/recruiting_automation-server' ENTER


# Create client window
tmux new-window -d -t $SESSION_NAME:3 -n 'client'
tmux select-window -t $SESSION_NAME:3
tmux split-window -h
tmux split-window -v

tmux select-pane -t 0
tmux send 'cd ~/code/toggle/recruiting_automation-client-web' ENTER 'vim' ENTER
tmux select-pane -t 1
tmux send 'cd ~/code/toggle/recruiting_automation-client-web' ENTER 'vim ~/code/working_notes/recruiting_web.js.rb' ENTER
tmux select-pane -t 2
tmux send 'cd ~/code/toggle/recruiting_automation-client-web' ENTER

# Attach to this session
tmux attach -t $SESSION_NAME
