#!/usr/bin/env bash

# Set starting dir
cd ~/code

# Create Session
SESSION_NAME=baseApp
tmux new-session -d -s $SESSION_NAME

# Create running window
tmux select-window -t $SESSION_NAME:1
tmux rename-window 'running'
tmux split-window -h
tmux split-window -v
tmux select-pane -t 0
tmux split-window -v

tmux select-pane -t 0
tmux send 'cd ~/code/api-base' ENTER 'foreman start' ENTER
tmux select-pane -t 1
tmux send 'cd ~/code/ember-client-base' ENTER 'sleep 2' ENTER 'ember s' ENTER

# Create server window
tmux new-window -d -t $SESSION_NAME:2 -n 'server'
tmux select-window -t $SESSION_NAME:2
tmux split-window -h
tmux split-window -v

tmux select-pane -t 0
tmux send 'cd ~/code/api-base' ENTER 'vim' ENTER
tmux select-pane -t 1
tmux send 'cd ~/code/api-base' ENTER 'vim ~/code/working_notes/api-base.rb' ENTER
tmux select-pane -t 2
tmux send 'cd ~/code/api-base' ENTER

# Create client window
tmux new-window -d -t $SESSION_NAME:3 -n 'client'
tmux select-window -t $SESSION_NAME:3
tmux split-window -h
tmux split-window -v

tmux select-pane -t 0
tmux send 'cd ~/code/ember-client-base' ENTER 'vim' ENTER
tmux select-pane -t 1
tmux send 'cd ~/code/ember-client-base' ENTER 'vim ~/code/working_notes/ember-client-base.js' ENTER
tmux select-pane -t 2
tmux send 'cd ~/code/ember-client-base' ENTER

# Attach to this session
tmux attach -t $SESSION_NAME
