#!/usr/bin/env bash

SESSION_NAME=${PWD##*/}

tmux new-session -d -s $SESSION_NAME
tmux new-window -d -t $SESSION_NAME:1 -n 'edit'
tmux new-window -d -t $SESSION_NAME:2 -n 'server'
tmux new-window -d -t $SESSION_NAME:3 -n 'console'
tmux new-window -d -t $SESSION_NAME:4 -n 'guard'
tmux new-window -d -t $SESSION_NAME:5 -n 'pg'

tmux send -t $SESSION_NAME:1 'vim .' ENTER
tmux send -t $SESSION_NAME:2 'rails s' ENTER
tmux send -t $SESSION_NAME:3 'rails c' ENTER
tmux send -t $SESSION_NAME:4 'guard' ENTER
tmux send -t $SESSION_NAME:5 'psql -h localhost -p 5432 -U postgres' ENTER

tmux select-window -t $SESSION_NAME:5
tmux split-window -v
tmux resize-pane -D 10
tmux send 'vim scratchpad.sql' ENTER

tmux select-window -t $SESSION_NAME:1
tmux split-window -v
tmux resize-pane -D 10
tmux rename-window 'edit'

tmux attach -t $SESSION_NAME
